### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by zdmta** [Wopee-io/playwright-ai-bot-demo#4]
```[tasklist]
### Tasks
- [ ] https://github.com/Wopee-io/playwright-ai-bot-demo/issues/5
- [ ] https://github.com/Wopee-io/playwright-ai-bot-demo/issues/6
- [ ] https://github.com/Wopee-io/playwright-ai-bot-demo/issues/7
- [ ] https://github.com/Wopee-io/playwright-ai-bot-demo/issues/8
- [ ] https://github.com/Wopee-io/playwright-ai-bot-demo/issues/9
- [ ] https://github.com/Wopee-io/playwright-ai-bot-demo/issues/10
```

**Comment by zdmta** [comment]
maybe consider option to connect already running browser instance, so user of bot can start crawling after some manual interaction (like login..)
https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp
